def getACCESS_TOKEN():
    return 'XXXX'
def getACCESS_SECRET():
    return 'XXXX'
def getCONSUMER_KEY():
    return 'XXXX'
def getCONSUMER_SECRET():
    return 'XXXX'
def getDataFileName():
    return "twitterData.txt"
